[package]
name = "traits"
version = "0.1.0"
authors = ["k1r1m1 <kirimi@paygoenergy.co>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
